name: alpine
channels:
  - conda-forge
  - defaults
dependencies:
  - gmsh
  - jax
  - jaxopt
  - numpy
  - pygmo
  - python
  - python-gmsh
  - trame
  - ipywidgets
  - scipy
  - scikit-learn
  - pyvista
  - typeguard
  - yaml
  - pygraphviz
  - pip
  - pip:
      - git+https://github.com/cpml-au/dctkit
      - git+https://github.com/cpml-au/deap
      - ray
      - pygmsh
      - tox
      - mygrad
