name: alpine
channels:
  - conda-forge
  - defaults
dependencies:
  - gmsh
  - jax
  - jaxopt
  - numpy
  - pygmo
  - python<3.11
  - python-gmsh
  - petsc4py
  - jupyterlab
  - trame
  - ipywidgets
  - scipy
  - scikit-learn
  - pyvista
  - typeguard
  - yaml
  - pygraphviz
  - joblib
  - pip
  - pip:
      - git+https://github.com/alucantonio/dctkit
      - git+https://github.com/alucantonio/deap
      - ray
      - pygmsh
      - tox
