# copy from environment.yaml in project root
name: readthedocs
channels:
  - conda-forge
  - defaults
dependencies:
  - gmsh
  - jax
  - jaxopt
  - numpy
  - pygmo
  - python<3.11
  - python-gmsh
  - petsc4py
  - jupyterlab
  - trame
  - ipywidgets
  - scipy
  - scikit-learn
  - pyvista
  - pygraphviz
  - typeguard
  - yaml
  - joblib
  - pip:
      - sphinx-rtd-theme
      - myst-parser[linkify]
      - sphinx>=3.2.1
      - git+https://github.com/alucantonio/dctkit
      - git+https://github.com/alucantonio/deap
      - ray
      - pygmsh
